import Head from 'next/head'
import Navbar from '../public/components/Navbar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Vanessa Sibley | Front-End Developer | Web3 </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
    </div>
  )
}
