import Head from 'next/head'
import About from '../public/components/About';
import Contact from '../public/components/Contact';
import { Hero } from '../public/components/Hero';
import Navbar from "../public/components/Navbar";
import Projects from '../public/components/Projects';
import Skills from "../public/components/Skills";

export default function Home() {
  return (
    <div>
      <Head>
        <html lang='en' />
        <title>Vanessa Sibley | Front-End Developer | Web3 </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <About />
      <Skills />
      <Projects />
      <Contact />
    </div>
  )
}
